export default {
  COLORS: {
    DEFAULT: '#FF6335',
    PRIMARY: '#FF6335',
    SECONDARY: '#F7FAFC',
    LABEL: '#FE2472',
    INFO: '#61A1A0',
    ERROR: '#F5365C',
    SUCCESS: '#2DCE89',
    WARNING: '#FB6340',
    TEXT: '#32325D',
    MUTED: '#8898AA',
    INPUT: '#DCDCDC',
    INPUT_SUCCESS: '#7BDEB2',
    INPUT_ERROR: '#FCB3A4',
    ACTIVE: '#FF6335',
    BUTTON_COLOR: '#9C26B0',
    PLACEHOLDER: '#9FA5AA',
    SWITCH_ON: '#018E98',
    SWITCH_OFF: '#D4D9DD',
    GRADIENT_START: '#FF6335',
    GRADIENT_END: '#FCAF16',
    PRICE_COLOR: '#EAD5FB',
    BORDER_COLOR: '#E7E7E7',
    BLOCK: '#E7E7E7',
    ICON: '#172B4D',
    HEADER: '#525F7F',
    BORDER: '#CAD1D7',
    WHITE: '#FFFFFF',
    BLACK: '#000000',
  },
  BRANDS: {
    twitter: {iconName: 'twitter', iconFamily: 'font-awesome-5', color: '#1DA1F2'},
    facebook: {iconName: 'facebook-f', iconFamily: 'font-awesome-5', color: '#3B5999'},
    dribbble: {iconName: 'dribbble', iconFamily: 'font-awesome-5', color: '#EA4C89'},
    instagram: {iconName: 'instagram', iconFamily: 'font-awesome-5', color: '#F56040'},
    whatsapp: {iconName: 'whatsapp', iconFamily: 'font-awesome-5', color: '#128C7E'},
    rappi: {iconName: 'rappi', iconFamily: 'ooup', color: '#FA3D22'},
    adobe: {iconName: 'adobe', iconFamily: 'font-awesome-5', color: '#ed2224'},
    airbnb: {iconName: 'airbnb', iconFamily: 'ooup', color: '#FF5A5F'},
    amazon: {iconName: 'amazon', iconFamily: 'font-awesome-5', color: '#FF9900'},
    lyft: {iconName: 'lyft', iconFamily: 'font-awesome-5', color: '#FF00BF'},
    snap: {iconName: 'snapchat-ghost', iconFamily: 'font-awesome-5', color: '#FFFC00'},
    spotify: {iconName: 'spotify', iconFamily: 'font-awesome-5', color: '#1DB954'},
    youtube: {iconName: 'youtube', iconFamily: 'font-awesome-5', color: '#FF0000'},
    mcdonalds: {iconName: 'mcdonalds', iconFamily: 'ooup', color: '#FFC72C'},
    netflix: {iconName: 'netflix', iconFamily: 'material-community', color: '#E50914'},
    uber: {iconName: 'uber', iconFamily: 'font-awesome-5', color: '#000000'},
    linkedin: {iconName: 'linkedin', iconFamily: 'font-awesome-5', color: '#2867B2'},
    bitcoin: {iconName: 'bitcoin', iconFamily: 'font-awesome-5', color: '#f2a900'},
    ooup: {iconName: 'ooup', iconFamily: 'ooup', color: '#FF6335'},
  }
};
