/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:55307068-36e5-4a2e-8349-05eab287c200",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_9CJRZZLXj",
    "aws_user_pools_web_client_id": "730tgoinesg2knqsd5r03lgck4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://slmru3idunc5rowif635m56qu4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
